# -*- coding: utf-8 -*-
"""
Manual validation scenario: MDrive Unprotected_Left_Turn/1 ego route running
through native OpenCDA (real PerceptionManager/LocalizationManager/V2XManager)
with the CP-X MPC planner bridge driving the vehicle.

This is a hand-built one-off test (not generated by import_mdrive_scenario.py)
to validate a single point before automating anything: overwriting
vehicle_manager.agent.initial_global_route with MDrive's literal polyline
after create_vehicle_manager() runs its own two-point GlobalRoutePlanner
trace, so CPXMPCPlannerBridge._active_global_route_points() sees the real
MDrive route instead of OpenCDA's own re-derived path.
"""

import math

import carla

import opencda.scenario_testing.utils.sim_api as sim_api
from opencda.core.common.cav_world import CavWorld
from opencda.planning_module.opencda_bridge.debug_viewer import OpenCDADebugViewer
from opencda.scenario_testing.evaluations.evaluate_manager import \
    EvaluationManager
from opencda.scenario_testing.utils.yaml_utils import add_current_time


# The other 5 ego candidates from Unprotected_Left_Turn/1's actors_manifest.json
# (we only drive Vehicle 1 -- these get spawned as plain autopilot background
# traffic instead, matching import_mdrive_scenario.py's multi-ego demotion).
# (x, y, z, yaw_deg, target_speed_kmh)
OTHER_EGO_SPAWN_POINTS = [
    (-65.793825, 84.491147, 0.3, -179.933155, 28.8),  # Vehicle 2 (8.0 m/s)
    (-163.802, 91.379, 0.3, 0.071620, 25.2),          # Vehicle 3 (7.0 m/s) -- close to ego's own start lane
    (-73.634, 84.482, 0.3, -179.942704, 28.8),        # Vehicle 4 (8.0 m/s)
    (-83.634, 84.471, 0.3, -179.928380, 25.2),        # Vehicle 5 (7.0 m/s)
    (-93.634, 84.460, 0.3, -179.928380, 25.2),        # Vehicle 6 (7.0 m/s)
]


def _spawn_other_ego_npcs(world, carla, blueprint_library, traffic_manager_port):
    """Spawn MDrive's other ego candidates as plain autopilot background
    traffic so the scenario isn't a single lonely car -- mirrors what
    import_mdrive_scenario.py does for the planning_module pipeline."""

    candidates = blueprint_library.filter("vehicle.tesla.model3")
    blueprint = candidates[0] if candidates else blueprint_library.filter("vehicle.*")[0]

    npc_actors = []
    for x, y, z, yaw_deg, speed_kmh in OTHER_EGO_SPAWN_POINTS:
        transform = carla.Transform(
            carla.Location(x=x, y=y, z=z),
            carla.Rotation(yaw=yaw_deg),
        )
        actor = world.try_spawn_actor(blueprint, transform)
        if actor is None:
            print(f"[MDRIVE TEST] Failed to spawn background NPC at ({x:.1f}, {y:.1f}) -- spot likely occupied.")
            continue
        actor.set_autopilot(True, traffic_manager_port)
        npc_actors.append(actor)
        print(f"[MDRIVE TEST] Spawned background NPC at ({x:.1f}, {y:.1f}), autopilot enabled.")
    return npc_actors


def _set_spectator_transform(spectator, ego_vehicle):
    transform = ego_vehicle.get_transform()
    yaw_rad = math.radians(float(transform.rotation.yaw))
    location = transform.location + carla.Location(
        x=-10.0 * math.cos(yaw_rad),
        y=-10.0 * math.sin(yaw_rad),
        z=4.5,
    )
    spectator.set_transform(carla.Transform(
        location,
        carla.Rotation(pitch=-15.0, yaw=float(transform.rotation.yaw), roll=0.0),
    ))


def _densify_between(carla_map, from_waypoint, to_location, step_m):
    """Walk from_waypoint towards to_location along the real lane geometry,
    inserting intermediate waypoints every step_m so consecutive route points
    never imply a bigger heading change than the lane's true curvature.

    Returns the list of intermediate waypoints (not including from_waypoint),
    ending at (or near) to_location.
    """

    inserted = []
    current = from_waypoint
    remaining_m = current.transform.location.distance(to_location)
    guard = 0
    while remaining_m > step_m and guard < 200:
        guard += 1
        candidates = list(current.next(step_m) or [])
        if not candidates:
            break
        # Prefer whichever candidate actually moves closer to to_location --
        # next() can return multiple lane options at junctions.
        current = min(candidates, key=lambda wp: wp.transform.location.distance(to_location))
        inserted.append(current)
        remaining_m = current.transform.location.distance(to_location)
    return inserted


def _inject_literal_route(vehicle_manager, scenario_params, carla_map, *, densify_step_m=1.5, densify_threshold_m=2.5):
    """Overwrite the agent's global route with MDrive's literal polyline.

    create_vehicle_manager() already called set_destination(spawn, destination),
    which populated agent.initial_global_route via OpenCDA's own
    GlobalRoutePlanner (two points only). We replace it here so
    CPXMPCPlannerBridge._active_global_route_points() follows MDrive's actual
    waypoint-by-waypoint path instead.

    MDrive's own point spacing is uneven -- straight segments are sparse (2-4m)
    but so are sharp turns, which means a big heading change gets packed into
    one reference segment and the CP-X reference pipeline effectively cuts the
    corner (chord instead of arc). When consecutive literal points are farther
    apart than densify_threshold_m, we walk the real lane geometry via
    waypoint.next(step_m) to fill in the gap instead of leaving it sparse.
    """

    route_waypoints = list(scenario_params.get("mdrive", {}).get("route_waypoints", []) or [])
    if not route_waypoints:
        print("[MDRIVE TEST] No mdrive.route_waypoints found in config; keeping OpenCDA's own route.")
        return

    raw_carla_waypoints = []
    for point in route_waypoints:
        x, y, z, _yaw_deg = [float(value) for value in point]
        location = carla.Location(x=x, y=y, z=z)
        waypoint = carla_map.get_waypoint(location)
        if waypoint is not None:
            raw_carla_waypoints.append(waypoint)

    if not raw_carla_waypoints:
        print("[MDRIVE TEST] Failed to resolve any CARLA waypoints for the literal route; keeping OpenCDA's own route.")
        return

    densified_waypoints = [raw_carla_waypoints[0]]
    inserted_count = 0
    for waypoint in raw_carla_waypoints[1:]:
        previous = densified_waypoints[-1]
        gap_m = previous.transform.location.distance(waypoint.transform.location)
        if gap_m > densify_threshold_m:
            inserted = _densify_between(carla_map, previous, waypoint.transform.location, densify_step_m)
            densified_waypoints.extend(inserted)
            inserted_count += len(inserted)
        densified_waypoints.append(waypoint)

    literal_route = [(waypoint, None) for waypoint in densified_waypoints]
    vehicle_manager.agent.initial_global_route = literal_route
    print(
        f"[MDRIVE TEST] Overwrote agent.initial_global_route with "
        f"{len(literal_route)} waypoints ({len(raw_carla_waypoints)} literal MDrive points + "
        f"{inserted_count} inserted to keep gaps <= {densify_threshold_m}m)."
    )


def run_scenario(opt, scenario_params):
    cav_world = None
    scenario_manager = None
    eval_manager = None
    debug_viewer = None
    single_cav_list = []
    npc_actors = []
    try:
        scenario_params = add_current_time(scenario_params)

        cav_world = CavWorld(opt.apply_ml)

        scenario_manager = sim_api.ScenarioManager(
            scenario_params,
            opt.apply_ml,
            opt.version,
            town="Town05",
            cav_world=cav_world,
        )

        if opt.record:
            scenario_manager.client.start_recorder("mdrive_test_left_turn.log", True)

        single_cav_list = scenario_manager.create_vehicle_manager(application=["single"])

        _inject_literal_route(
            single_cav_list[0],
            scenario_params,
            scenario_manager.carla_map,
        )

        traffic_manager = scenario_manager.client.get_trafficmanager()
        npc_actors = _spawn_other_ego_npcs(
            scenario_manager.world,
            carla,
            scenario_manager.world.get_blueprint_library(),
            traffic_manager.get_port(),
        )

        eval_manager = EvaluationManager(
            scenario_manager.cav_world,
            script_name="mdrive_test_left_turn",
            current_time=scenario_params["current_time"],
        )

        if OpenCDADebugViewer.enabled_from_env() and single_cav_list:
            debug_viewer = OpenCDADebugViewer(
                world=scenario_manager.world,
                carla_module=carla,
                ego_vehicle=single_cav_list[0].vehicle,
            )

        spectator = scenario_manager.world.get_spectator()
        while True:
            scenario_manager.tick()
            cav_world.tick()
            _set_spectator_transform(spectator, single_cav_list[0].vehicle)

            for single_cav in single_cav_list:
                single_cav.update_info()
                control = single_cav.run_step()
                single_cav.vehicle.apply_control(control)

            if debug_viewer is not None:
                debug_viewer.render(single_cav_list)

    finally:
        if eval_manager is not None:
            eval_manager.evaluate()

        if opt.record and scenario_manager is not None:
            scenario_manager.client.stop_recorder()

        if debug_viewer is not None:
            debug_viewer.destroy()

        if scenario_manager is not None:
            scenario_manager.close()

        for v in single_cav_list:
            v.destroy()
        for actor in npc_actors:
            actor.destroy()
